recapture the changes that were in 1.7 but only locally commited
Signed-off-by: das_deniz <das_deniz@comcast.net>

diff --git a/geninitrd b/geninitrd
--- a/geninitrd
+++ b/geninitrd
@@ -1,22 +1,41 @@
 #!/bin/bash
 
+if [[ ! -x /usr/bin/unsquashfs ]] ; then
+  echo "you need to install the squashfs pkg"
+  exit 1
+fi
+
+if [[ ! -x /sbin/depmod ]] ; then
+  echo "you need to install the module-init-tools pkg"
+  exit 1
+fi
+
 pushd()
 {
     builtin pushd "$@" > /dev/null
+    if [[ "$?" == "1" ]]; then
+      echo "exiting - unable to pushd into $@"
+      exit 1
+    fi
 }
 popd()
 {
-    builtin popd "$@" > /dev/null
+    if [ -z "$@" ] ; then
+      builtin popd > /dev/null
+    else
+      builtin popd "$@" > /dev/null
+    fi
 }
 
 ## Create a new initrd.baracus
 ##
 ##
 
-DATADIR=workload
-DSTDIR=$DATADIR/initrd.dir
 [ ! -z "$1" ] && INITRD_IMG=$1 
-[ -z "$INITRD_IMG" ] &&  INITRD_IMG=initrd.opensuse-11.3
+
+# set the default for the vanilla - we should have a list here and a generation loop
+
+[ -z "$INITRD_IMG" ] && INITRD_IMG=initrd.opensuse-11.3
 
 if [[ "$INITRD_IMG" == "initrd.opensuse-11.3" ]]; then
     KERNEL="2.6.34-12-default"
@@ -26,7 +45,20 @@ else
     KERNEL=""
 fi
 
-echo "using initrd: $INITRD_IMG"
+DATADIR=`pwd`/workload
+DSTDIR="$DATADIR/$INITRD_IMG.dir"
+BA_APPS="pxewait busybox.dban baracus.dban baracus.image baracus.mcast baracus.clone baracus.register lshw-static.B.02.15.x86 dbclient shellexec ipmitool"
+BIN_APPLETS="ash cp dd dmesg echo grep ls tar date mv"
+USR_BIN_APPLETS="clear dwipe sort tr wc"
+
+export KERNEL DATADIR INITRD_IMG DSTDIR BA_APPS BIN_APPLETS USR_BIN_APPLETS
+
+if [[ ! -f "$DATADIR/$INITRD_IMG" ]] ; then
+  echo "unable to find specified initrd: $DATADIR/$INITRD_IMG"
+  exit 1
+else
+  echo "using initrd: $DATADIR/$INITRD_IMG"
+fi
 
 [[ -d $DSTDIR ]] && rm -rf $DSTDIR
 mkdir -p $DSTDIR
@@ -34,13 +66,12 @@ mkdir -p $DSTDIR
 ## Extract the image
 ##
 
-pushd $DSTDIR
+[[ -d $DSTDIR ]] && pushd $DSTDIR
   zcat ../$INITRD_IMG | cpio --quiet -id  
   
   ## copy-in the baracus data
   ##
   mkdir -p usr/bin/
-  BA_APPS="pxewait busybox.dban baracus.dban baracus.image baracus.mcast baracus.clone baracus.register lshw-static.B.02.15.x86 dbclient shellexec ipmitool"
   for i in $BA_APPS; do
         cp ../$i usr/bin/.
   done
@@ -68,15 +99,13 @@ pushd $DSTDIR
     ln -s ../usr/bin/busybox.udpcast udp-receiver
     ln -s ../usr/bin/busybox.udpcast udp-sender
 
-    APPLETS="ash cp dd dmesg echo grep ls tar date mv"
-    for i in $APPLETS; do
+    for i in $BIN_APPLETS; do
         ln -s ../usr/bin/busybox.dban $i
     done
   popd
   
   pushd usr/bin
-    APPLETS="clear dwipe sort tr wc"
-    for i in $APPLETS; do
+    for i in $USR_BIN_APPLETS; do
         ln -s ../../usr/bin/busybox.dban $i
     done
   popd
@@ -88,31 +117,38 @@ pushd $DSTDIR
     mv tmppasswd passwd
   popd
 
-  pushd parts
-    unsquashfs 00_lib &> /dev/null
-    cp ../../$INITRD_IMG-modules/ipmi* squashfs-root/lib/modules/$KERNEL/initrd/
-     KPATH=`pwd`/squashfs-root
-    pushd squashfs-root/lib/modules/$KERNEL
+  # modern non-xen kernels have fs pkg'd in parts
+  if [[ -d parts ]] ; then
+    pushd parts
+      unsquashfs 00_lib &> /dev/null
+      cp ../../$INITRD_IMG-modules/ipmi* squashfs-root/lib/modules/$KERNEL/initrd/
+    
+      export KPATH=`pwd`/squashfs-root         # var is location sensitive KPATH must be here
+      pushd squashfs-root/lib/modules/$KERNEL
         depmod -a --basedir $KPATH $KERNEL
+      popd
+      rm 00_lib
+      mksquashfs squashfs-root/ 00_lib &> /dev/null
+      rm -Rf squashfs-root/
     popd
-    rm 00_lib
-    mksquashfs squashfs-root/ 00_lib &> /dev/null
-    rm -Rf squashfs-root/
-  popd
+  else
+    # when we need we'll modifiy so we can add modules to xen initrd here too
+    echo "not working with parts dir - hope this is a xen initrd or it won't have ipmi"
+  fi
   
   ## create the new image
   ##
-  [ -f ../initrd.baracus ] && rm ../initrd.baracus
-  find . | cpio --quiet --create --format='newc' > ../initrd.baracus
+  [ -f ../$INITRD_IMG.baracus ] && rm ../$INITRD_IMG.baracus
+  find . | cpio --quiet --create --format='newc' > ../$INITRD_IMG.baracus
 popd
 
 pushd $DATADIR
-  gzip initrd.baracus
-  mv initrd.baracus.gz initrd.baracus
+  gzip $INITRD_IMG.baracus
+  mv $INITRD_IMG.baracus.gz $INITRD_IMG.baracus
 popd
 
 [[ -d $DSTDIR ]] && rm -rf $DSTDIR
 
 ## complete
 ##
-echo "initrd.baracus generation complete"
+echo "completed: $DATADIR/$INITRD_IMG.baracus"
